# evaluator prompts
EVALUATOR_RULES_PROMPT = "evaluator.RULES_PROMPT"
EVALUATOR_SUB_AGENTS_SENTENCE_COMPLETION_CONTEXT_PROMPT = "agents.evaluator.sentence_completion.CONTEXT_PROMPT"
EVALUATOR_SUB_AGENTS_INFO_DESCRIPTION_CONTEXT_PROMPT = "agents.evaluator.info_description.CONTEXT_PROMPT"
EVALUATOR_SUB_AGENTS_OPINION_ESSAY_CONTEXT_PROMPT = "agents.evaluator.opinion_essay.CONTEXT_PROMPT"

# corrector prompts
CORRECTOR_RULES_PROMPT = "corrector.RULES_PROMPT"
CORRECTOR_SUB_AGENTS_INFO_DESCRIPTION_CONTEXT_PROMPT = "agents.corrector.info_description.CONTEXT_PROMPT"
CORRECTOR_SUB_AGENTS_OPINION_ESSAY_CONTEXT_PROMPT = "agents.corrector.opinion_essay.CONTEXT_PROMPT"
