# evaluator prompts (Common)
EVALUATOR_RULES_PROMPT = "evaluator.RULES_PROMPT"
EVALUATOR_CONTEXT_TEMPLATE_PROMPT = "evaluator.CONTEXT_TEMPLATE_PROMPT"

# evaluator sub agents
# Sentence Completion (SC)
EVALUATOR_SC_CONTEXT_RUBRIC_PROMPT = "evaluator.sc.CONTEXT_RUBRIC_PROMPT"
EVALUATOR_SC_FEWSHOT_PROMPT = "evaluator.sc.FEWSHOT_PROMPT"

# Info Description (ID)
EVALUATOR_ID_CONTEXT_RUBRIC_PROMPT = "evaluator.id.CONTEXT_RUBRIC_PROMPT"
EVALUATOR_ID_FEWSHOT_PROMPT = "evaluator.id.FEWSHOT_PROMPT"
EVALUATOR_ID_RULES_PROMPT = "evaluator.id.RULES_PROMPT"

# Opinion Essay (OE)
EVALUATOR_OE_CONTEXT_RUBRIC_PROMPT = "evaluator.oe.CONTEXT_RUBRIC_PROMPT"
EVALUATOR_OE_FEWSHOT_PROMPT = "evaluator.oe.FEWSHOT_PROMPT"
EVALUATOR_OE_RULES_PROMPT = "evaluator.oe.RULES_PROMPT"


# corrector prompts (Common)
CORRECTOR_RULES_PROMPT = "corrector.RULES_PROMPT"
CORRECTOR_CONTEXT_TEMPLATE_PROMPT = "corrector.CONTEXT_TEMPLATE_PROMPT"

# corrector sub agents
# Info Description (ID)
CORRECTOR_ID_CONTEXT_RUBRIC_PROMPT = "corrector.id.CONTEXT_RUBRIC_PROMPT"
CORRECTOR_ID_FEWSHOT_PROMPT = "corrector.id.FEWSHOT_PROMPT"
CORRECTOR_ID_RULES_PROMPT = "corrector.id.RULES_PROMPT"

# Opinion Essay (OE)
CORRECTOR_OE_CONTEXT_RUBRIC_PROMPT = "corrector.oe.CONTEXT_RUBRIC_PROMPT"
CORRECTOR_OE_FEWSHOT_PROMPT = "corrector.oe.FEWSHOT_PROMPT"
CORRECTOR_OE_RULES_PROMPT = "corrector.oe.RULES_PROMPT"
