export const PROMPT_KEYS = {
  // Evaluator Details (Context Rubric Only)
  EVALUATOR_SC_CONTEXT_RUBRIC_PROMPT: "evaluator.sc.CONTEXT_RUBRIC_PROMPT",
  EVALUATOR_ID_CONTEXT_RUBRIC_PROMPT: "evaluator.id.CONTEXT_RUBRIC_PROMPT",
  EVALUATOR_OE_CONTEXT_RUBRIC_PROMPT: "evaluator.oe.CONTEXT_RUBRIC_PROMPT",

  // Corrector Details (Context Rubric Only)
  CORRECTOR_ID_CONTEXT_RUBRIC_PROMPT: "corrector.id.CONTEXT_RUBRIC_PROMPT",
  CORRECTOR_OE_CONTEXT_RUBRIC_PROMPT: "corrector.oe.CONTEXT_RUBRIC_PROMPT",
} as const;

export const PROMPT_KEY_LABELS: Record<(typeof PROMPT_KEYS)[keyof typeof PROMPT_KEYS], string> = {
  [PROMPT_KEYS.EVALUATOR_SC_CONTEXT_RUBRIC_PROMPT]: "채점 기준",
  [PROMPT_KEYS.EVALUATOR_ID_CONTEXT_RUBRIC_PROMPT]: "채점 기준",
  [PROMPT_KEYS.EVALUATOR_OE_CONTEXT_RUBRIC_PROMPT]: "채점 기준",

  [PROMPT_KEYS.CORRECTOR_ID_CONTEXT_RUBRIC_PROMPT]: "첨삭 기준",
  [PROMPT_KEYS.CORRECTOR_OE_CONTEXT_RUBRIC_PROMPT]: "첨삭 기준",
};
